#!/bin/bash

cd $(dirname $0)
taskName=$1
taskArgs=${@:2}

case $taskName in
    "generate")
    cd src
    for pkg in $taskArgs; do
        cd $pkg
        go generate
        cd ..
    done
    ;;
esac